#!/usr/bin/env python3
"""
Exact governed stochastic-programming / MILP-style baseline over an explicit
blind-sequence table.

What it does
------------
Given a CSV whose rows are complete blind sequences and whose columns contain
loss/risk/event metrics, this script solves the same lexicographic governed
objective as the paper:

  1. deterministic governed baseline:
       choose exactly one sequence;
       first satisfy all event budgets;
       then minimize the requested selector among feasible rows;
       if infeasible, return least-violating row.

  2. randomized/LP relaxation baseline:
       choose a distribution over sequences;
       event budgets are linear constraints;
       objective is linear in the selected metric.

The deterministic problem is the finite-scenario stochastic-programming/MILP
formulation with one binary variable z_nu per sequence. Because exactly one
sequence must be selected, solving it by complete table scan is equivalent to
solving that one-hot MILP, and is more robust than depending on CP-SAT/Gurobi.
The script also writes an optional LP file documenting the exact MILP.

Expected CSV columns
--------------------
- sequence column: one of seq, sequence, policy, actions
- objective column: mean by default, or use --selector COLUMN
- event columns: either specified by --budget name=value, or autodetected as
  columns beginning with prob_ or p_.

If no --budget arguments are provided, default budgets are inferred from file
name for the existing suite and public transfers.
"""

from __future__ import annotations

import argparse
import csv
import glob
import json
import math
import os
import re
from dataclasses import dataclass
from typing import Dict, Iterable, List, Optional, Tuple

try:
    import numpy as np
except Exception:  # pragma: no cover
    np = None

try:
    from scipy.optimize import linprog
except Exception:  # pragma: no cover
    linprog = None

SEQ_COL_CANDIDATES = ["seq", "sequence", "policy", "actions", "commitment"]
OBJECTIVE_CANDIDATES = ["mean", "governed_mean", "loss_mean", "expected_loss", "score"]

DEFAULT_BUDGETS: Dict[str, Dict[str, float]] = {
    # Original exact hard suite
    "bfsp_hard": {"prob_catastrophic": 0.075, "prob_degraded": 0.3, "prob_rejected": 0.36},
    "bcst_hard": {"prob_catastrophic": 0.13, "prob_toxicity": 0.34, "prob_moderate_harm": 0.82},
    "bged_hard": {"prob_catastrophic": 0.22, "prob_no_benefit": 0.24, "prob_offtarget": 0.24, "prob_immune": 0.22},
    "bsp_hard": {"prob_catastrophic": 0.075, "prob_degraded": 0.3, "prob_rejected": 0.36, "prob_shortage": 0.36},
    # Original exact stress-unobservable suite
    "bfsp_stress_unobservable": {"prob_catastrophic": 0.0, "prob_degraded": 0.0},
    "bcst_stress_unobservable": {"prob_catastrophic": 0.0, "prob_toxicity": 0.0},
    "bged_stress_unobservable": {"prob_catastrophic": 0.0, "prob_offtarget": 0.0, "prob_immune": 0.0},
    "bsp_stress_unobservable": {"prob_catastrophic": 0.0, "prob_degraded": 0.0, "prob_shortage": 0.0},
    # Public SysAdmin transfer from your current results
    "sysadmin_transfer_hard_H6": {"prob_catastrophic": 0.075, "prob_degraded": 0.3, "prob_shortage": 0.3},
    "sysadmin_transfer_stress_unobservable_H3": {"prob_catastrophic": 0.0, "prob_degraded": 0.0, "prob_shortage": 0.0},
    # New public transfer templates generated by run_public_transfer_extra.py
    "tiger_transfer_hard_H4": {"prob_catastrophic": 0.20, "prob_degraded": 0.45},
    "tiger_transfer_stress_unobservable_H2": {"prob_catastrophic": 0.0, "prob_degraded": 0.0},
    "rocksample_transfer_hard_H5": {"prob_catastrophic": 0.15, "prob_degraded": 0.35, "prob_shortage": 0.35},
    "rocksample_transfer_stress_unobservable_H3": {"prob_catastrophic": 0.0, "prob_degraded": 0.0},
}


def safe_float(x: object, default: float = math.nan) -> float:
    try:
        if x is None:
            return default
        s = str(x).strip()
        if s == "" or s.lower() in {"nan", "none", "null"}:
            return default
        return float(s)
    except Exception:
        return default


def parse_budget_items(items: Optional[List[str]]) -> Dict[str, float]:
    out: Dict[str, float] = {}
    for item in items or []:
        if "=" not in item:
            raise SystemExit(f"Bad --budget {item!r}; expected name=value")
        k, v = item.split("=", 1)
        out[k.strip()] = float(v)
    return out


def infer_instance_name(path: str) -> str:
    base = os.path.basename(path)
    base = re.sub(r"_all_sequences\.csv$", "", base)
    base = re.sub(r"_summary\.csv$", "", base)
    return base


def infer_budgets(instance: str, columns: List[str]) -> Dict[str, float]:
    if instance in DEFAULT_BUDGETS:
        return {k: v for k, v in DEFAULT_BUDGETS[instance].items() if k in columns}
    # Conservative fallback: if no known default, use any budget-like columns in metadata columns.
    # Otherwise require user-supplied budgets.
    return {}


def find_seq_col(columns: List[str]) -> str:
    for c in SEQ_COL_CANDIDATES:
        if c in columns:
            return c
    raise SystemExit(f"No sequence column found. Tried {SEQ_COL_CANDIDATES}; columns={columns}")


def find_obj_col(columns: List[str], selector: str) -> str:
    if selector in columns:
        return selector
    if selector == "mean":
        for c in OBJECTIVE_CANDIDATES:
            if c in columns:
                return c
    raise SystemExit(f"Objective column {selector!r} not found in columns: {columns}")


def read_rows(path: str) -> List[Dict[str, str]]:
    with open(path, newline="") as f:
        return list(csv.DictReader(f))


def violation(row: Dict[str, str], budgets: Dict[str, float], weights: Dict[str, float]) -> float:
    total = 0.0
    for k, b in budgets.items():
        x = safe_float(row.get(k), 0.0)
        total += weights.get(k, 1.0) * max(0.0, x - b)
    return total


def is_feasible(row: Dict[str, str], budgets: Dict[str, float], tol: float = 1e-12) -> bool:
    return all(safe_float(row.get(k), 0.0) <= b + tol for k, b in budgets.items())


def solve_deterministic(rows: List[Dict[str, str]], seq_col: str, obj_col: str, budgets: Dict[str, float], weights: Dict[str, float]) -> Dict[str, object]:
    feasible = [r for r in rows if is_feasible(r, budgets)]
    if feasible:
        best = min(feasible, key=lambda r: (safe_float(r.get(obj_col)), r.get(seq_col, "")))
        return {
            "det_status": "feasible",
            "det_feasible_count": len(feasible),
            "det_seq": best.get(seq_col, ""),
            "det_objective": safe_float(best.get(obj_col)),
            "det_violation": 0.0,
            "det_event_usage_json": json.dumps({k: safe_float(best.get(k), 0.0) for k in budgets}, sort_keys=True),
        }
    best = min(rows, key=lambda r: (violation(r, budgets, weights), safe_float(r.get(obj_col)), r.get(seq_col, "")))
    return {
        "det_status": "infeasible_least_violation",
        "det_feasible_count": 0,
        "det_seq": best.get(seq_col, ""),
        "det_objective": safe_float(best.get(obj_col)),
        "det_violation": violation(best, budgets, weights),
        "det_event_usage_json": json.dumps({k: safe_float(best.get(k), 0.0) for k in budgets}, sort_keys=True),
    }


def solve_lp_mixture(rows: List[Dict[str, str]], seq_col: str, obj_col: str, budgets: Dict[str, float]) -> Dict[str, object]:
    if linprog is None or np is None:
        return {"lp_status": "scipy_unavailable"}
    n = len(rows)
    c = np.array([safe_float(r.get(obj_col), 0.0) for r in rows], dtype=float)
    A_ub = []
    b_ub = []
    for k, b in budgets.items():
        A_ub.append([safe_float(r.get(k), 0.0) for r in rows])
        b_ub.append(b)
    A_eq = [np.ones(n)]
    b_eq = [1.0]
    res = linprog(
        c,
        A_ub=np.array(A_ub, dtype=float) if A_ub else None,
        b_ub=np.array(b_ub, dtype=float) if b_ub else None,
        A_eq=np.array(A_eq, dtype=float),
        b_eq=np.array(b_eq, dtype=float),
        bounds=[(0.0, 1.0)] * n,
        method="highs",
    )
    if not res.success:
        return {"lp_status": "infeasible_or_failed", "lp_message": res.message}
    x = res.x
    support = [(float(w), rows[i].get(seq_col, ""), safe_float(rows[i].get(obj_col))) for i, w in enumerate(x) if w > 1e-7]
    support.sort(reverse=True)
    usage = {}
    for k in budgets:
        usage[k] = float(sum(x[i] * safe_float(rows[i].get(k), 0.0) for i in range(n)))
    return {
        "lp_status": "feasible",
        "lp_objective": float(res.fun),
        "lp_support_size": len(support),
        "lp_top_support_json": json.dumps(support[:8]),
        "lp_event_usage_json": json.dumps(usage, sort_keys=True),
    }


def write_lp_file(path: str, rows: List[Dict[str, str]], seq_col: str, obj_col: str, budgets: Dict[str, float]) -> None:
    os.makedirs(os.path.dirname(path), exist_ok=True)
    def var(i: int) -> str:
        return f"z_{i}"
    with open(path, "w") as f:
        f.write("\\ Exact one-hot deterministic governed stochastic program\n")
        f.write("Minimize\n obj: ")
        terms = [f"{safe_float(r.get(obj_col), 0.0):.12g} {var(i)}" for i, r in enumerate(rows)]
        f.write(" + ".join(terms) + "\n")
        f.write("Subject To\n")
        f.write(" one_sequence: " + " + ".join(var(i) for i in range(len(rows))) + " = 1\n")
        for k, b in budgets.items():
            terms = [f"{safe_float(r.get(k), 0.0):.12g} {var(i)}" for i, r in enumerate(rows)]
            f.write(f" budget_{k}: " + " + ".join(terms) + f" <= {b:.12g}\n")
        f.write("Binary\n")
        for i in range(len(rows)):
            f.write(f" {var(i)}\n")
        f.write("End\n")


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--csv", action="append", help="Specific all-sequences CSV. May be used multiple times.")
    ap.add_argument("--glob", default=None, help="Glob for all-sequences CSV files.")
    ap.add_argument("--out", default="paper_tables/table_exact_sp_baseline.csv")
    ap.add_argument("--selector", default="mean", help="Objective column to minimize; default resolves to mean-like column.")
    ap.add_argument("--budget", action="append", help="Budget constraint name=value. If omitted, use defaults by instance name.")
    ap.add_argument("--weight", action="append", help="Violation weight name=value; default 1 for each budget.")
    ap.add_argument("--write-lp-dir", default="exports_lp", help="Directory for LP formulation files; use empty string to disable.")
    args = ap.parse_args()

    paths: List[str] = []
    if args.glob:
        paths.extend(glob.glob(args.glob))
    if args.csv:
        paths.extend(args.csv)
    paths = sorted(set(paths))
    if not paths:
        raise SystemExit("No CSV files found. Use --csv or --glob.")

    cli_budgets = parse_budget_items(args.budget)
    weights = parse_budget_items(args.weight)
    out_rows: List[Dict[str, object]] = []

    for path in paths:
        rows = read_rows(path)
        if not rows:
            continue
        columns = list(rows[0].keys())
        instance = infer_instance_name(path)
        seq_col = find_seq_col(columns)
        obj_col = find_obj_col(columns, args.selector)
        budgets = cli_budgets or infer_budgets(instance, columns)
        if not budgets:
            print(f"[WARN] skipping {path}: no budgets provided/inferred")
            continue
        weights_use = {k: weights.get(k, 1.0) for k in budgets}
        det = solve_deterministic(rows, seq_col, obj_col, budgets, weights_use)
        lp = solve_lp_mixture(rows, seq_col, obj_col, budgets)
        if args.write_lp_dir:
            write_lp_file(os.path.join(args.write_lp_dir, f"{instance}_{obj_col}.lp"), rows, seq_col, obj_col, budgets)
        out = {
            "instance": instance,
            "csv": path,
            "num_sequences": len(rows),
            "objective_column": obj_col,
            "budgets_json": json.dumps(budgets, sort_keys=True),
        }
        out.update(det)
        out.update(lp)
        if out.get("lp_status") == "feasible" and det.get("det_status") == "feasible":
            out["lp_minus_det"] = float(out["lp_objective"]) - float(out["det_objective"])
        out_rows.append(out)
        print(f"[OK] {instance}: det={det['det_status']} obj={det['det_objective']} lp={lp.get('lp_status')}")

    os.makedirs(os.path.dirname(args.out) or ".", exist_ok=True)
    fieldnames = sorted({k for r in out_rows for k in r.keys()})
    with open(args.out, "w", newline="") as f:
        w = csv.DictWriter(f, fieldnames=fieldnames)
        w.writeheader()
        w.writerows(out_rows)
    print(f"[OK] wrote {args.out}")

if __name__ == "__main__":
    main()
